# docker-compose.yml
# last updated: 10-5-25
# credit: Claude Sonnet 4.5

version: "3.8"

services:
  hworld-server:
    build: .
    image: hworld-server:latest
    container_name: hworld-server
    ports:
      - "28080:28080"
    volumes:
      - ./data:/data
    environment:
      - HWORLD_HOST=0.0.0.0
      - HWORLD_PORT=28080
      - HWORLD_BUFFER=1024
      - HWORLD_VERBOSE=true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
